---

- name: Ensure vault docker install
  ansible.builtin.include_tasks: docker_install.yml
  when: docker_install

- name: Ensure hold docker packages versions (hold)
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop: 
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose-plugin
  when:          docker_hold_packages_versions
  ignore_errors: "{{ ansible_check_mode }}"

- name: Ensure unhold docker packages versions (install)
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: install
  loop: 
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose-plugin
  when:          docker_unhold_packages_versions
  ignore_errors: "{{ ansible_check_mode }}"

...