---

- name: Ensure /etc/docker
  ansible.builtin.file:
    path:  /etc/docker
    state: directory
    mode:  u=rw,g=r
  when: not docker_manipulate_iptables_rules

- name: Ensure docker not manipulating iptables
  ansible.builtin.template:
    src:  daemon.json.j2
    dest: /etc/docker/daemon.json
    mode: u=rw,g=r
  when: not docker_manipulate_iptables_rules

- name: Ensure /etc/apt/keyrings
  ansible.builtin.file:
    dest:  /etc/apt/keyrings
    state: directory
    mode:  u=rwx,g=rx,o=rx

- name: Ensure Docker repository signing key
  ansible.builtin.shell:
    cmd:     curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg    
    creates: /etc/apt/keyrings/docker.gpg

- name: Ensure Docker repository
  ansible.builtin.shell:
    cmd: echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
    creates: /etc/apt/sources.list.d/docker.list

- name: Ensure apt cache update
  ansible.builtin.apt:
    update_cache: yes

- name: Ensure install Docker Engine     
  ansible.builtin.apt:
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin

- name: Ensure hold docker packages versions
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop: 
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose-plugin
  when: docker_hold_package_version

...